import { Task } from '@/app/lib/types';

export const tasks: Task[] = [
  {
    id: '1',
    title: 'Implement login functionality',
    description: 'Build user login form with email and password validation using React and Firebase.',
    status: 'in-progress',
    assignee: 'Ivan',
    tags: ['frontend', 'auth', 'react'],
    createdAt: new Date('2025-09-08'),
  },
  {
    id: '2',
    title: 'Set up PostgreSQL database',
    description: 'Install and configure PostgreSQL database for the staging environment.',
    status: 'done',
    assignee: 'Bob',
    tags: ['backend', 'database', 'devops'],
    createdAt: new Date('2025-09-01'),
  },
  {
    id: '3',
    title: 'Design homepage wireframes',
    description: 'Create low-fidelity wireframes for the new homepage layout using Figma.',
    status: 'done',
    assignee: 'Carol',
    tags: ['design', 'ux', 'figma'],
    createdAt: new Date('2025-08-30'),
  },
  {
    id: '4',
    title: 'Write unit tests for user service',
    description: 'Add comprehensive unit tests to the user service logic in the backend.',
    status: 'scheduled',
    assignee: 'Dave',
    tags: ['backend', 'testing', 'jest'],
    createdAt: new Date('2025-09-10'),
  },
  {
    id: '5',
    title: 'Create CI/CD pipeline',
    description: 'Set up GitHub Actions to build and deploy the application on every push to main.',
    status: 'in-progress',
    assignee: 'Eve',
    tags: ['devops', 'github-actions', 'ci/cd'],
    createdAt: new Date('2025-09-07'),
  },
  {
    id: '6',
    title: 'Optimize image loading',
    description: 'Lazy load images and convert to WebP format for faster performance.',
    status: 'scheduled',
    assignee: 'Frank',
    tags: ['frontend', 'performance', 'images'],
    createdAt: new Date('2025-09-11'),
  },
  {
    id: '7',
    title: 'Conduct usability testing',
    description: 'Run usability tests with 5 users and compile findings.',
    status: 'done',
    assignee: 'Grace',
    tags: ['ux', 'research', 'testing'],
    createdAt: new Date('2025-08-29'),
  },
  {
    id: '8',
    title: 'Refactor API error handling',
    description: 'Standardize error responses across all REST endpoints.',
    status: 'in-progress',
    assignee: 'Heidi',
    tags: ['backend', 'api', 'refactor'],
    createdAt: new Date('2025-09-05'),
  },
  {
    id: '9',
    title: 'Update project documentation',
    description: 'Revise the README and add setup instructions.',
    status: 'scheduled',
    assignee: 'Ivan',
    tags: ['docs', 'readme', 'setup'],
    createdAt: new Date('2025-09-11'),
  },
  {
    id: '10',
    title: 'Create onboarding checklist',
    description: 'Develop a checklist for onboarding new engineers.',
    status: 'done',
    assignee: 'Judy',
    tags: ['hr', 'onboarding', 'process'],
    createdAt: new Date('2025-09-02'),
  },
  {
    id: '11',
    title: 'Implement dark mode',
    description: 'Add toggleable dark mode support to the UI.',
    status: 'scheduled',
    assignee: 'Karl',
    tags: ['frontend', 'theme', 'ui'],
    createdAt: new Date('2025-09-11'),
  },
  {
    id: '12',
    title: 'Deploy app to production',
    description: 'Coordinate with ops to deploy the latest build to production.',
    status: 'in-progress',
    assignee: 'Laura',
    tags: ['release', 'production', 'ops'],
    createdAt: new Date('2025-09-09'),
  },
  {
    id: '13',
    title: 'Fix 500 error on login',
    description: 'Investigate and fix the intermittent 500 error during login.',
    status: 'done',
    assignee: 'Karl',
    tags: ['bug', 'backend', 'auth'],
    createdAt: new Date('2025-09-06'),
  },
  {
    id: '14',
    title: 'Add role-based access control',
    description: 'Implement RBAC to restrict access to admin routes.',
    status: 'scheduled',
    assignee: 'Nina',
    tags: ['security', 'backend', 'rbac'],
    createdAt: new Date('2025-09-11'),
  },
  {
    id: '15',
    title: 'Analyze user engagement metrics',
    description: 'Pull analytics data and report user retention trends.',
    status: 'in-progress',
    assignee: 'Nina',
    tags: ['analytics', 'data', 'report'],
    createdAt: new Date('2025-09-10'),
  },
];